name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Log in to the Github container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      -
        name: Build local image
        run: docker build . --file Dockerfile --tag zadanie2test:v1

      -
        name: Scan local image
        id: image-scan
        run: | 
            curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sh install-scout.sh
            docker scout cves --exit-code --only-severity critical zadanie2test:v1
            echo "SCAN_RESULT=$?" >> "$GITHUB_ENV"

      - 
        name: Build and push Docker image
        id: push
        run: | 
            docker build . --tag ghcr.io/${{ vars.GH_USERNAME_LOWERCASE }}/zadanie2:v1
            docker push ghcr.io/${{ vars.GH_USERNAME_LOWERCASE }}/zadanie2:v1